language: php

php:
  - 5.6
  - 7.0

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - phpunit --coverage-clover=coverage.xml
  - php coverage-checker.php coverage.xml 90

after_success:
    - bash <(curl -s https://codecov.io/bash)
